purdue_words = [
'boiler up',
'hammer down',
'purdue pete',
'bell tower',
'fountain run',
'boiler gold rush',
'boiler cold rush',
'boilermaker special',
'iu sucks',
'engineering fountain',
'loeb fountain',
'breakfast club',
'grand prix',
'zach edey',
'paint crew',
'slayter hill',
'matt painter',
'black and gold',
'hail purdue',
'triple xxx',
'west lafayette',
'caleb furst',
'clapping circle',
'john purdue',
'niel armstrong',
'unfinished block p',
'elliot hall',
'chenflix',
'daddy daniels',
'mung chiang',
'lawson',
'beering',
'amelia earhart'
]

halloween_words = [
'pumpkin carving',
'jack o lantern',
'haunted house',
'vampire',
'witch',
'apple cider',
'candycorn',
'trick or treat',
'friday the thirteenth',
'pumpkin spice latte',
'frankenstein',
'nightmare on elm street',
'grim reaper',
'corn maze',
'mummified',
'cauldron',
'cobwebs',
'cemetery',
'bewitching',
'black cat',
'ghoulish',
'paranormal',
'phantom',
'chainsaw',
'magic potion',
'boogeyman',
'costume party',
'pumpkin pie',
'goosebumps',
'casper',
'dracula',
'all hallows eve',
'spooky story'
]

christmas_words = [
'santa claus',
'north pole',
'reindeer',
'mistletoe',
'candy cane',
'rudolph',
'stocking',
'elves',
'jack frost',
'frosty the snowman',
'yuletide',
'plum pudding',
'gingerbread house',
'northern lights',
'garland',
'carolers',
'christmas tree',
'nazareth',
'hot chocolate',
'charlie brown christmas',
'jingle bell rock',
'polar express',
'snowman',
'feliz navidad',
'cookies and milk',
'last christmas'
'peppermint'
'snow ice cream',
'hallmark movies',
'black ice',
'nutcracker',
'jesus christ',
'mother mary'
]